apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.ports.apiContainerPort }}
      name: {{ .Values.ports.apiname | quote }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
